=== tmsns/homey-json-schema/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "App",
    "type": "object",
    "definitions": {
        "argsArray": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "autocomplete",
                            "dropdown",
                            "text",
                            "number",
                            "device"
                        ]
                    },
                    "filter": {
                        "type": "string"
                    },
                    "placeholder": {
                        "$ref": "#/definitions/translatableObject"
                    },
                    "values": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "label": {
                                    "$ref": "#/definitions/translatableObject"
                                }
                            }
                        }
                    }
                }
            }
        },
        "imageObject": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "large": {
                    "type": "string",
                    "description": "Location of a large image. eg. ./somedir/some-large-image.jpg"
                },
                "small": {
                    "type": "string",
                    "description": "Location of a small image. eg. ./somedir/some-small-image.jpg"
                }
            }  
        },
        "translatableObject": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "en": {
                    "type": "string",
                    "description": "English translation of the object."                         
                },
                "nl": {
                    "type": "string",
                    "description": "Dutch translation of the object."
                }
            }
        },
        "setting": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"  
                },
                "label": {
                    "$ref": "#/definitions/translatableObject",
                    "description": "Label of the setting."
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/setting"
                    }
                }
            } 
        }
    },
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "description": "the schema to be used for validation of the json files"
        },
        "id": { 
            "type": "string"
        },
        "category": {
            "anyOf": [
                {
                    "type": "array",
                    "items": { 
                        "type": "string"                
                    }
                },
                {
                    "type": "string"
                }
            ]
        },
        "version": { 
            "type": "string"
        },
        "compatibility": { 
            "type": "string"
        },
        "name": { 
            "$ref": "#/definitions/translatableObject",
            "description": "Name of the Homey app."
        },
        "description": { 
            "$ref": "#/definitions/translatableObject",
            "description": "Description of the Homey app."
        },
        "author": { 
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name" : {
                    "type": "string"
                },
                "email" : {
                    "type": "string"
                },
                "website" : {
                    "type": "string"
                }
            }
        },
        "permissions": {
            "type": "array",
            "description": "all requested permissions of your app.",
            "items": {
                "type": "string",
                "enum": [
                    "homey:manager:speech-output",
                    "homey:manager:speech-input",
                    "homey:manager:ledring"                 
                ]
            }
        },
        "speech": {
            "type": "array",
            "description": "all speech objects of your app.",
            "items": {
                "title": "connection",
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "id": {
                        "description": "Speech object",
                        "type": "string"
                    },
                    "importance": {
                        "description": "This is the importance of your speech object.",
                        "type": "number"
                    },
                    "triggers": {
                        "description": "Triggers of the speech object.",
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "en" : {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "nl" : {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
        
                    }
                }
            }
        },
        "drivers": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "$ref": "#/definitions/translatableObject",
                        "description": "Name of the driver."
                    },
                    "images": {
                        "$ref": "#/definitions/imageObject"
                    },
                    "class": {
                        "type": "string"
                    },
                    "capabilities": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "pair": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                                "id" : {
                                    "type": "string"
                                },
                                "template" : {
                                    "type": "string"
                                },
                                "navigation": {
                                    "type": "object",
                                    "additionalProperties": false,
                                    "properties": {
                                        "next": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "settings": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/setting"
                        }
                    }
                }                
            }
        },
        "images": {
            "$ref": "#/definitions/imageObject"
        },
        "flow": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "triggers" : {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "id" : {
                                "type": "string"
                            },
                            "title": {
                                "type" : "object"
                            },
                            "fluidArgs" : {
                                "type": "boolean"
                            },
                            "args": {
                                "$ref": "#/definitions/argsArray"
                            },
                            "tokens": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "additionalProperties": false,
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "title": {
                                            "$ref": "#/definitions/translatableObject"
                                        },
                                        "example": {
                                            "$ref": "#/definitions/translatableObject"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "conditions" : {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "id" : {
                                "type": "string"
                            },
                            "title": {
                                "type" : "object"
                            },
                            "args": {
                                "$ref": "#/definitions/argsArray"
                            }
                        }
                    }
                },
                "actions": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "id" : {
                                "type": "string"
                            },
                            "title": {
                                "type" : "object"
                            },
                            "fluidArgs" : {
                                "type": "boolean"
                            },
                            "args": {
                                "$ref": "#/definitions/argsArray"
                            }
                        }
                    }
                }
            }            
        }
    }
}

=== tmsns/homey-json-schema/samples/nl.marvinschenkel.kodi/app.json
{
  "$schema": "schema.json",
  "id": "nl.marvinschenkel.kodi",
  "name": {
    "en": "Kodi for Homey",
    "nl": "Kodi voor Homey"
  },
  "description": {
    "en": "Control your Kodi device with Homey!",    
    "nl": "Bestuur je Kodi apparaat met Homey!"
  },
  "version": "1.1.1",
  "compatibility": ">=0.8.24 || 1.x",
  "category": [
    "music",
    "video"
  ],
  "author": {
    "name": "Marvin Schenkel",
    "email": "marvinschenkel@gmail.com",
    "website": "https://linkedin.com/in/marvinschenkel"
  },
  "speech":[
    {
      "id": "kodi_play_movie",
      "importance": 1,
      "triggers" : {
        "en" : ["play movie"],
        "nl" : ["speel film", "speel de film"]
      }
    },
    {
      "id": "kodi_play_tvshow",
      "importance": 1,
      "triggers" : {
        "en" : ["play tv show"],
        "nl" : ["speel serie", "speel de serie"]
      }
    },
    {
      "id": "kodi_play_music",
      "importance": 1,
      "triggers" : {
        "en" : ["play music"],
        "nl": ["speel muziek"]
      }
    },
    {
      "id": "kodi_play_pause",
      "importance": 1,
      "triggers" : {
        "en" : ["pause", "resume"],
        "nl" : ["pauze", "speel", "hervat"]
      }
    },
    {
      "id": "kodi_stop",
      "importance": 0.7,
      "triggers" : {
        "en" : ["stop", "exit", "quit"],
        "nl": ["stop"]
      }
    },
    {
      "id": "kodi_next",
      "importance": 0.7,
      "triggers": {
        "en" : ["next track"],
        "nl": ["volgende"]
      }
    },
    {
      "id": "kodi_previous",
      "importance": 0.7,
      "triggers": {
        "en" : ["previous track"],
        "nl": ["vorige"]
      }
    },
    {
       "id": "kodi_play_latest_episode",
       "importance": 1,
       "triggers": {
         "en": ["play latest episode of", "play the latest episode of", "play latest episode", "play latest episode of"],
         "nl": ["speel de laatste aflevering", "speel de laatste aflevering van", "speel laatste aflevering"]
       }
    }
  ],
  "drivers": [
    {
      "id": "kodi",
      "name": {
        "en": "Kodi"
      },
      "images": {
        "large": "./drivers/kodi/assets/images/large.png",
        "small": "./drivers/kodi/assets/images/small.png"
      },
      "class": "videoplayer",
      "capabilities": [ "play", "pause", "stop" ],
      "pair": [
        {
          "id": "configure_kodi"
        }
        ,
        {
          "id": "add_kodis",
          "template": "add_devices"
        }
      ],
      "settings": [
        {
          "type": "group",
          "label": {
            "en": "Kodi settings",
            "nl": "Kodi instellingen"
          },
          "children": [
            {
              "id": "host",
              "type": "text",
              "label": {
                "en": "(Local) IP Address of Kodi",
                "nl": "(Lokale) IP adres van Kodi"
              }
            },
            {
              "id": "tcpport",
              "type": "text",
              "label": {
                "en": "TCP Port",
                "nl": "TCP Poort"
              }
            }
          ]
        }
      ]
    }
  ],
  "images":{
    "large":"./assets/images/large.png",
    "small":"./assets/images/small.png"
  },
  "flow":	{
    "triggers":[
      {
        "id":"kodi_movie_start",
        "title": {
          "en":"A movie has started",          
          "nl":"Een film begint"
        },
        "args": [
          {
            "name": "kodi",
            "type": "device",
            "filter": "driver_uri=homey:app:nl.marvinschenkel.kodi&driver_id=kodi",
            "placeholder": { 
              "en": "Which Kodi device", 
              "nl": "Welk Kodi apparaat" 
             }
          }
        ],
        "tokens":[
          {
            "name":"movie_title",
            "title": {
              "en":"Title",
              "nl":"Titel"
            },
            "example":{
              "en":"Finding Nemo",
              "nl":"Finding Nemo"
            }
          }
        ]
      },
      {
        "id":"kodi_episode_start",
        "title": {
          "en":"An episode has started",
          "nl":"Een aflevering begint"
        },
        "args": [
          {
            "name": "kodi",
            "type": "device",
            "filter": "driver_uri=homey:app:nl.marvinschenkel.kodi&driver_id=kodi"
          }
        ],
        "tokens":[
          {
            "name":"tvshow_title",
            "title": {
              "en":"Show",
              "nl":"Serie"
            },
            "example":{
              "en":"The Walking Dead",
              "nl":"The Walking Dead"
            }
          },
          {
            "name":"episode_title",
            "title": {
              "en":"Episode",
              "nl":"Aflevering"
            },
            "example":{
              "en":"First Time Again",
              "nl":"First Time Again"
            }
          },
          {
            "name":"season",
            "title": {
              "en":"Sea #",
              "nl":"Sei #"
            },
            "example":{
              "en":"1",
              "nl":"1"
            }
          },
          {
            "name":"episode",
            "title": {
              "en":"Ep #",
              "nl":"Afl #"
            },
            "example":{
              "en":"2",
              "nl":"2"
            }
          }
        ]
      },
      {
        "id":"kodi_pause",
        "title": {
          "en":"Kodi has been paused",
          "nl": "Kodi is gepauzeerd"
        },
        "args": [
          {
            "name": "kodi",
            "type": "device",
            "filter": "driver_uri=homey:app:nl.marvinschenkel.kodi&driver_id=kodi"
          }
        ]
      },
      {
        "id":"kodi_resume",
        "title": {
          "en":"Kodi has been resumed",
          "nl":"Kodi begint weer af te spelen"
        },
        "args": [
          {
            "name": "kodi",
            "type": "device",
            "filter": "driver_uri=homey:app:nl.marvinschenkel.kodi&driver_id=kodi"
          }
        ]
      },
      {
        "id":"kodi_stop",        
        "title": {
          "en":"Kodi has been stopped",
          "nl": "Kodi is gestopt"
        },
        "args": [
          {
            "name": "kodi",
            "type": "device",
            "filter": "driver_uri=homey:app:nl.marvinschenkel.kodi&driver_id=kodi"
          }
        ]
      }
    ],
    "actions":[
      {
        "id": "play_movie_kodi",
        "title": {
          "en" : "Play a movie on Kodi",
          "nl":"Speel een film af op Kodi"
        },
        "fluidArgs": true,
        "args":[
          {
            "name": "kodi",
            "type": "device",
            "filter": "driver_uri=homey:app:nl.marvinschenkel.kodi&driver_id=kodi"
          },
          {
            "name": "movie_title",
            "type": "text",
            "placeholder" : {
              "en" : "Type a movie title that's in your library",
              "nl": "Voer een film uit je bibliotheek in"
            }
          }
        ]
      },
      {
        "id": "pause_resume_kodi",
        "title": {
          "en" : "Pause / resume playback on Kodi",
          "nl" : "Pauzeer / hervat Kodi"
        },
        "fluidArgs": true,
        "args":[
          {
            "name": "kodi",
            "type": "device",
            "filter": "driver_uri=homey:app:nl.marvinschenkel.kodi&driver_id=kodi"
          }
        ]
      },
      {
        "id": "stop_kodi",
        "title": {
          "en" : "Stop playback on Kodi",
          "nl" : "Stop afspelen op Kodi"
        },
        "fluidArgs": true,
        "args":[
          {
            "name": "kodi",
            "type": "device",
            "filter": "driver_uri=homey:app:nl.marvinschenkel.kodi&driver_id=kodi"
          }
        ]
      }
    ]
  }
  ,
  "permissions": [
    "homey:manager:speech-output",
    "homey:manager:speech-input",
    "homey:manager:ledring"
  ]
}
